DROP TABLE IF EXISTS INTERNAL_USER;

CREATE TABLE INTERNAL_USER (
    ID SERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255),
    CREATED_DATETIME VARCHAR(255),
    ACTIVE BOOLEAN
);